export const products = [
  {
    id: "prod-001",
    name: "Classic Blue Jeans",
    image: "/images/products/blue-jeans.jpeg",
    price: 49.99,
    category: "Trousers",
    tags: ["jeans", "denim", "casual"],
    inStock: true,
    sizes: ["S", "M", "L", "XL"],
    rating: 4.5,
  },
  {
    id: "prod-002",
    name: "Black Hoodie",
    image: "/images/products/black-hoodie.jpeg",
    price: 39.99,
    category: "Hoodies",
    tags: ["hoodie", "black", "casual"],
    inStock: true,
    sizes: ["M", "L", "XL"],
    rating: 4.2,
  },
  {
    id: "prod-003",
    name: "Slim Fit Chinos",
    image: "/images/products/chinos.jpeg",
    price: 44.99,
    category: "Trousers",
    tags: ["chinos", "slim fit", "workwear"],
    inStock: false,
    sizes: ["S", "M", "L"],
    rating: 4.1,
  },
  {
    id: "prod-004",
    name: "Oversized Sweatshirt",
    image: "/images/products/oversized-sweatshirt.jpg",
    price: 29.99,
    category: "Sweatshirts",
    tags: ["oversized", "streetwear", "sweatshirt"],
    inStock: true,
    sizes: ["M", "L", "XL"],
    rating: 4.7,
  },
  {
    id: "prod-005",
    name: "Grey Joggers",
    image: "/images/products/grey-joggers.jpg",
    price: 34.99,
    category: "Trousers",
    tags: ["joggers", "athleisure", "comfort"],
    inStock: true,
    sizes: ["S", "M", "L"],
    rating: 4.3,
  },
  {
    id: "prod-006",
    name: "Beige Cargo Pants",
    image: "/images/products/cargo-pants.jpg",
    price: 42.99,
    category: "Trousers",
    tags: ["cargo", "utility", "streetwear"],
    inStock: false,
    sizes: ["M", "L", "XL"],
    rating: 4.6,
  },
  {
    id: "prod-007",
    name: "White Pullover Hoodie",
    image: "/images/products/white-hoodie.jpg",
    price: 39.99,
    category: "Hoodies",
    tags: ["pullover", "hoodie", "white"],
    inStock: true,
    sizes: ["S", "M", "L"],
    rating: 4.4,
  },
  {
    id: "prod-008",
    name: "Navy Blue Sweater",
    image: "/images/products/navy-sweater.jpg",
    price: 41.99,
    category: "Sweatshirts",
    tags: ["sweater", "navy", "casual"],
    inStock: true,
    sizes: ["M", "L", "XL"],
    rating: 4.5,
  },
  {
    id: "prod-009",
    name: "Denim Jacket",
    image: "/images/products/denim-jacket.jpg",
    price: 59.99,
    category: "Jackets",
    tags: ["denim", "jacket", "layer"],
    inStock: true,
    sizes: ["M", "L", "XL"],
    rating: 4.8,
  },
  {
    id: "prod-010",
    name: "Graphic Sweatshirt",
    image: "/images/products/graphic-sweatshirt.jpg",
    price: 33.99,
    category: "Sweatshirts",
    tags: ["graphic", "sweatshirt", "design"],
    inStock: false,
    sizes: ["S", "M", "L"],
    rating: 4.0,
  },
  {
    id: "prod-011",
    name: "Olive Green Hoodie",
    image: "/images/products/olive-hoodie.jpg",
    price: 38.99,
    category: "Hoodies",
    tags: ["green", "hoodie", "warm"],
    inStock: true,
    sizes: ["S", "M", "L", "XL"],
    rating: 4.6,
  },
  {
    id: "prod-012",
    name: "Black Cargo Joggers",
    image: "/images/products/black-cargo.jpg",
    price: 45.99,
    category: "Trousers",
    tags: ["black", "joggers", "cargo"],
    inStock: true,
    sizes: ["M", "L"],
    rating: 4.4,
  },
  {
    id: "prod-013",
    name: "Striped Polo Shirt",
    image: "/images/products/polo-striped.jpg",
    price: 24.99,
    category: "Shirts",
    tags: ["polo", "striped", "smart casual"],
    inStock: true,
    sizes: ["M", "L", "XL"],
    rating: 3.9,
  },
  {
    id: "prod-014",
    name: "Fleece Hoodie",
    image: "/images/products/fleece-hoodie.jpg",
    price: 46.99,
    category: "Hoodies",
    tags: ["fleece", "hoodie", "winter"],
    inStock: false,
    sizes: ["S", "M"],
    rating: 4.8,
  },
  {
    id: "prod-015",
    name: "Slim Fit Trousers",
    image: "/images/products/slim-fit.jpg",
    price: 48.99,
    category: "Trousers",
    tags: ["slim", "trousers", "modern"],
    inStock: true,
    sizes: ["M", "L", "XL"],
    rating: 4.2,
  },
  {
    id: "prod-016",
    name: "Crew Neck Sweatshirt",
    image: "/images/products/crew-sweatshirt.jpg",
    price: 32.99,
    category: "Sweatshirts",
    tags: ["crew neck", "basic", "casual"],
    inStock: true,
    sizes: ["S", "M", "L"],
    rating: 4.0,
  },
  {
    id: "prod-017",
    name: "Quilted Bomber Jacket",
    image: "/images/products/bomber-jacket.jpg",
    price: 59.99,
    category: "Jackets",
    tags: ["quilted", "bomber", "fall"],
    inStock: true,
    sizes: ["M", "L", "XL"],
    rating: 4.6,
  },
  {
    id: "prod-018",
    name: "Light Grey Hoodie",
    image: "/images/products/light-grey-hoodie.jpg",
    price: 37.99,
    category: "Hoodies",
    tags: ["light grey", "hoodie", "soft"],
    inStock: true,
    sizes: ["S", "M", "L", "XL"],
    rating: 4.3,
  },
  {
    id: "prod-019",
    name: "Basic White Tee",
    image: "/images/products/white-tee.jpg",
    price: 19.99,
    category: "Shirts",
    tags: ["white", "t-shirt", "basic"],
    inStock: true,
    sizes: ["S", "M", "L", "XL"],
    rating: 4.1,
  },
  {
    id: "prod-020",
    name: "Streetwear Hoodie",
    image: "/images/products/streetwear-hoodie.jpg",
    price: 50.0,
    category: "Hoodies",
    tags: ["streetwear", "hoodie", "bold"],
    inStock: true,
    sizes: ["M", "L", "XL"],
    rating: 4.9,
  },
];

