export const products = [
  {
    id: "prod-001",
    name: "Classic Blue Jeans",
    image: "/images/products/blue-jeans.jpeg",
    price: 49.99,
    category: "Trousers",
    tags: ["jeans", "denim", "casual"],
    inStock: true,
    sizes: ["S", "M", "L", "XL"],
    rating: 4.5,
    description: "Timeless classic blue jeans with a comfortable fit and durable denim—perfect for everyday casual wear."
  },
  {
    id: "prod-002",
    name: "Black Hoodie",
    image: "/images/products/black-hoodie.jpeg",
    price: 39.99,
    category: "Hoodies",
    tags: ["hoodie", "black", "casual"],
    inStock: true,
    sizes: ["M", "L", "XL"],
    rating: 4.2,
    description: "Stay cozy and stylish with this soft black hoodie, ideal for layering or lounging."
  },
  {
    id: "prod-003",
    name: "Slim Fit Chinos",
    image: "/images/products/chinos.jpeg",
    price: 44.99,
    category: "Trousers",
    tags: ["chinos", "slim fit", "workwear"],
    inStock: false,
    sizes: ["S", "M", "L"],
    rating: 4.1,
    description: "Polished slim-fit chinos designed for comfort and sharp looks—great for both office and weekend vibes."
  },
  {
    id: "prod-004",
    name: "Oversized Sweatshirt",
    image: "/images/products/oversized-swarshirt.jpeg",
    price: 29.99,
    category: "Sweatshirts",
    tags: ["oversized", "streetwear", "sweatshirt"],
    inStock: true,
    sizes: ["M", "L", "XL"],
    rating: 4.7,
    description: "Level up your streetwear game with this ultra-comfy oversized sweatshirt made for chill days."
  },
  {
    id: "prod-005",
    name: "Grey Joggers",
    image: "/images/products/grey-joggers.jpeg",
    price: 34.99,
    category: "Trousers",
    tags: ["joggers", "athleisure", "comfort"],
    inStock: true,
    sizes: ["S", "M", "L"],
    rating: 4.3,
    description: "Relax or run errands in these sleek grey joggers—crafted for all-day movement and style."
  },
  {
    id: "prod-006",
    name: "Beige Cargo Pants",
    image: "/images/products/beige-cargo-pants.jpeg",
    price: 42.99,
    category: "Trousers",
    tags: ["cargo", "utility", "streetwear"],
    inStock: false,
    sizes: ["M", "L", "XL"],
    rating: 4.6,
    description: "Functional beige cargo pants with multiple pockets—perfect for utility and fashion-forward looks."
  },
  {
    id: "prod-007",
    name: "White Pullover Hoodie",
    image: "/images/products/white-hoodie.jpeg",
    price: 39.99,
    category: "Hoodies",
    tags: ["pullover", "hoodie", "white"],
    inStock: true,
    sizes: ["S", "M", "L"],
    rating: 4.4,
    description: "Clean, comfy, and classic—this white pullover hoodie brings effortless cool to your wardrobe."
  },
  {
    id: "prod-008",
    name: "Navy Blue Sweater",
    image: "/images/products/navy-sweater.jpeg",
    price: 41.99,
    category: "Sweatshirts",
    tags: ["sweater", "navy", "casual"],
    inStock: true,
    sizes: ["M", "L", "XL"],
    rating: 4.5,
    description: "A must-have navy sweater that’s warm, versatile, and perfect for laid-back elegance."
  },
  {
    id: "prod-009",
    name: "Denim Jacket",
    image: "/images/products/denim-jacket.jpeg",
    price: 59.99,
    category: "Jackets",
    tags: ["denim", "jacket", "layer"],
    inStock: true,
    sizes: ["M", "L", "XL"],
    rating: 4.8,
    description: "This classic denim jacket is your go-to layer for adding rugged style to any outfit."
  },
  {
    id: "prod-010",
    name: "Graphic Sweatshirt",
    image: "/images/products/graphic-sweatshirt.jpeg",
    price: 33.99,
    category: "Sweatshirts",
    tags: ["graphic", "sweatshirt", "design"],
    inStock: false,
    sizes: ["S", "M", "L"],
    rating: 4.0,
    description: "Make a statement with this bold graphic sweatshirt, featuring unique prints and comfy fabric."
  },
  {
    id: "prod-011",
    name: "Olive Green Hoodie",
    image: "/images/products/olive-hoodie.jpeg",
    price: 38.99,
    category: "Hoodies",
    tags: ["green", "hoodie", "warm"],
    inStock: true,
    sizes: ["S", "M", "L", "XL"],
    rating: 4.6,
    description: "Earthy and stylish, this olive green hoodie brings warm tones and a relaxed vibe."
  },
  {
    id: "prod-012",
    name: "Black Cargo Joggers",
    image: "/images/products/black-carrgo.jpeg",
    price: 45.99,
    category: "Trousers",
    tags: ["black", "joggers", "cargo"],
    inStock: true,
    sizes: ["M", "L"],
    rating: 4.4,
    description: "Tough meets comfy—these black cargo joggers offer a modern streetwear edge with utility flair."
  },
  {
    id: "prod-013",
    name: "Striped Polo Shirt",
    image: "/images/products/striped-polo-shirt.jpeg",
    price: 24.99,
    category: "Shirts",
    tags: ["polo", "striped", "smart casual"],
    inStock: true,
    sizes: ["M", "L", "XL"],
    rating: 3.9,
    description: "Keep it classy with this striped polo shirt—a smart casual essential for any wardrobe."
  },
  {
    id: "prod-014",
    name: "Fleece Hoodie",
    image: "/images/products/fleece-hoodie.jpeg",
    price: 46.99,
    category: "Hoodies",
    tags: ["fleece", "hoodie", "winter"],
    inStock: false,
    sizes: ["S", "M"],
    rating: 4.8,
    description: "Snuggle into this ultra-soft fleece hoodie—your perfect companion for chilly days and cozy nights."
  },
  {
    id: "prod-015",
    name: "Slim Fit Trousers",
    image: "/images/products/slim-fit-trousers.jpeg",
    price: 48.99,
    category: "Trousers",
    tags: ["slim", "trousers", "modern"],
    inStock: true,
    sizes: ["M", "L", "XL"],
    rating: 4.2,
    description: "Step out in confidence with these modern slim-fit trousers—clean lines, sharp style."
  },
  {
    id: "prod-016",
    name: "Crew Neck Sweatshirt",
    image: "/images/products/crew-neck.jpeg",
    price: 32.99,
    category: "Sweatshirts",
    tags: ["crew neck", "basic", "casual"],
    inStock: true,
    sizes: ["S", "M", "L"],
    rating: 4.0,
    description: "A comfy crew neck sweatshirt with a relaxed fit—your everyday essential with chill vibes."
  },
  {
    id: "prod-017",
    name: "Quilted Bomber Jacket",
    image: "/images/products/bomber-jacket.jpeg",
    price: 59.99,
    category: "Jackets",
    tags: ["quilted", "bomber", "fall"],
    inStock: true,
    sizes: ["M", "L", "XL"],
    rating: 4.6,
    description: "This quilted bomber jacket blends warmth and urban edge—perfect for fall fashion layering."
  },
  {
    id: "prod-018",
    name: "Light Grey Hoodie",
    image: "/images/products/light-grey-hoodie.jpeg",
    price: 37.99,
    category: "Hoodies",
    tags: ["light grey", "hoodie", "soft"],
    inStock: true,
    sizes: ["S", "M", "L", "XL"],
    rating: 4.3,
    description: "Brighten up your hoodie collection with this soft light grey piece—versatile and easy to style."
  },
  {
    id: "prod-019",
    name: "Basic White Tee",
    image: "/images/products/basic-white-tee.jpeg",
    price: 19.99,
    category: "Shirts",
    tags: ["white", "t-shirt", "basic"],
    inStock: true,
    sizes: ["S", "M", "L", "XL"],
    rating: 4.1,
    description: "The basic white tee you can’t live without—clean, crisp, and endlessly pairable."
  },
  {
    id: "prod-020",
    name: "Streetwear Hoodie",
    image: "/images/products/streetwear-hoodie.jpeg",
    price: 50.0,
    category: "Hoodies",
    tags: ["streetwear", "hoodie", "bold"],
    inStock: true,
    sizes: ["M", "L", "XL"],
    rating: 4.9,
    description: "Turn heads with this bold streetwear hoodie—urban style meets premium comfort."
  },
];
